### PR TITLE
#1345 Added support List1 on B-Frames for AVC video format

### PR DESCRIPTION
**Pull request by selenorks**
This is a fix for ISSUE #1345

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Thanks! PR seems fine, I check soon the PR with all files I have.

**Comment by selenorks** [comment]
Hi @JeromeMartinez, any news about the PR?

**Comment by JeromeMartinez** [comment]
I try to handle that today or tomorrow.

**Review by JeromeMartinez — APPROVED** [review]
i have no file demonstrating the issue, could you share one? I need only 1 frame.

**Comment by selenorks** [comment]
[Here is a stream](https://drive.google.com/file/d/1Z1YJckOZ8b1RfDpbpC8pbbp1TT_UvPHa/view?usp=sharing)
master version on command line: `MediaInfo.exe --ParseSpeed=1 -f bbb_b_frames.h264`
has output:
`Frame count                              : 599`
fixed version has output
`Frame count                              : 600`

**Comment by selenorks** [comment]
@JeromeMartinez Hi, any news about the PR?

**Pull request merged**
