### PR TITLE
File__Analyze::Get_MacRoman 

### LINKED ISSUE #1205: Crash File_Mpeg4::moov_trak_mdia_hdlr
stack only 
https://drdump.com/DumpGroup.aspx?ClientID=guest&DumpGroupID=1491492

изображение

 	[Inline Frame] FlylinkDC.exe!std::_WChar_traits<wchar_t>::length(const wchar_t *) Line 307	C++
 	[Inline Frame] FlylinkDC.exe!std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> >::assign(const wchar_t * const) Line 2676	C++
 	[Inline Frame] FlylinkDC.exe!ZenLib::Ztring::From_Unicode(const wchar_t *) Line 245	C++
 	[Inline Frame] FlylinkDC.exe!MediaInfoLib::File__Analyze::Get_MacRoman(unsigned __int64) Line 1394	C++
 	[Inline Frame] FlylinkDC.exe!MediaInfoLib::File__Analyze::Get_MacRoman(unsigned __int64 Bytes, ZenLib::Ztring &) Line 739	C++
>	FlylinkDC.exe!MediaInfoLib::File_Mpeg4::moov_trak_mdia_hdlr() Line 3843	C++
 	FlylinkDC.exe!MediaInfoLib::File_Mpeg4::moov_trak_mdia_minf_hdlr() Line 4437	C++
 	FlylinkDC.exe!MediaInfoLib::File_Mpeg4::Data_Parse() Line 1342	C++
 	FlylinkDC.exe!MediaInfoLib::File__Analyze::Data_Manage() Line 2378	C++
 	FlylinkDC.exe!MediaInfoLib::File__Analyze::Buffer_Parse() Line 1528	C++
 	FlylinkDC.exe!MediaInfoLib::File__Analyze::Open_Buffer_Continue_Loop() Line 1092	C++
 	FlylinkDC.exe!MediaInfoLib::File__Analyze::Open_Buffer_Continue(const unsigned char * ToAdd, unsigned int ToAdd_Size) Line 696	C++
 	FlylinkDC.exe!MediaInfoLib::MediaInfo_Internal::Open_Buffer_Continue(const unsigned char * ToAdd, unsigned int ToAdd_Size) Line 1341	C++
 	FlylinkDC.exe!MediaInfoLib::Reader_File::Format_Test_PerParser_Continue(MediaInfoLib::MediaInfo_Internal * MI) Line 791	C++
 	FlylinkDC.exe!MediaInfoLib::Reader_File::Format_Test_PerParser(MediaInfoLib::MediaInfo_Internal * MI, const std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > & File_Name) Line 323	C++
 	FlylinkDC.exe!MediaInfoLib::MediaInfo_Internal::ListFormats(const std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > & File_Name) Line 862	C++
 	FlylinkDC.exe!MediaInfoLib::Reader_File::Format_Test(MediaInfoLib::MediaInfo_Internal * MI, std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > File_Name) Line 239	C++
 	FlylinkDC.exe!MediaInfoLib::MediaInfo_Internal::Entry() Line 1089	C++
 	FlylinkDC.exe!MediaInfoLib::MediaInfo_Internal::Open(const std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> > & File_Name_) Line 844	C++

### PR DESCRIPTION
**Pull request by pavel-pimenov**
Try fix #1205

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Ouch... Good catch, but fix is actually easier:
`Temp[Bytes]=__T('\0');`
is the missing only line.

**Comment by pavel-pimenov** [comment]
for (size_t Pos=0; **Pos<=Bytes**; Pos++)
...
Pos<=Bytes ?

**Comment by JeromeMartinez** [comment]
> Pos<=Bytes ?

Oops (bis...), should be `Pos<Bytes` and `Temp[Bytes]=__T('\0');` right after the `for` loop for making more sense.

I'll retrieve a file using this code for being sure.

**Comment by JeromeMartinez** [comment]
I slightly modified the patch.
Thanks!

**Pull request merged**
