### PR TITLE
New format "Directory" when image sequence + audio file is detected

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Detect that an image sequence and an audio file are in a directory and are part of a package.
Classic usage : DPX + WAV.

As directory structure depends on the supplier, we need to adapt per supplier.
We start with this structure:
```
 title-of-work/
     title-of-work.wav
     dpx/
         title-of-work_0086880.dpx
         title-of-work_0086881.dpx
         ... etc ...
```

### CODE REVIEW

**Comment by kieranjol** [comment]
Oh wow, this is so cool!

**Comment by JeromeMartinez** [comment]
Example of output:
```
General
Complete name                            : title-of-work\
Format                                   : Directory
File size                                : 1.94 MiB
Duration                                 : 1 s 0 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 706 kb/s

Video
Format                                   : DPX
Format version                           : Version 1.0
Format_Compression                       : Raw
Format settings                          : Little / Packed
Muxing mode                              : DPX
Width                                    : 176 pixels
Height                                   : 144 pixels
Display aspect ratio                     : 1.222
Color space                              : RGB
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossless
Stream size                              : 1.85 MiB (96%)
Writing library                          : Lavc58.25.100
Color primaries                          : Linear
Source                                   : dpx\title-of-work_00000001.dpx
Source_Last                              : dpx\title-of-work_00000025.dpx

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Muxing mode                              : Wave
Codec ID                                 : 1
Duration                                 : 1 s 0 ms
Bit rate mode                            : Constant
Bit rate                                 : 705.6 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Stream size                              : 86.1 KiB (4%)
Writing library                          : Lavc58.25.100
Source                                   : title-of-work.wav
```

**Comment by kieranjol** [comment]
My god,is this what @mcampos-quinn got sponsorship for?

**Comment by JeromeMartinez** [comment]
Example of PBCore2 output:
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated at 2018-08-30T12:59:23Z by MediaInfoLib - v18.05 -->
<pbcoreInstantiationDocument xsi:schemaLocation="http://www.pbcore.org/PBCore/PBCoreNamespace.html https://raw.githubusercontent.com/WGBH/PBCore_2.1/master/pbcore-2.1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.pbcore.org/PBCore/PBCoreNamespace.html">
	<instantiationIdentifier source="File Name">title-of-work_00000001.dpx</instantiationIdentifier>
	<instantiationDate dateType="file modification">2018-08-30T12:21:43.697Z</instantiationDate>
	<instantiationDigital>video/x-directory</instantiationDigital>
	<instantiationStandard>Directory</instantiationStandard>
	<instantiationLocation>title-of-work\</instantiationLocation>
	<instantiationMediaType>Moving Image</instantiationMediaType>
	<instantiationFileSize unitsOfMeasure="byte">2030678</instantiationFileSize>
	<instantiationDuration>00:00:01:00</instantiationDuration>
	<instantiationDataRate unitsOfMeasure="bit/second">16245424</instantiationDataRate>
	<instantiationTracks>2</instantiationTracks>
	<instantiationChannelConfiguration>Track : 1 channel</instantiationChannelConfiguration>
	<instantiationEssenceTrack>
		<essenceTrackType>Video</essenceTrackType>
		<essenceTrackIdentifier source="ID" />
		<essenceTrackIdentifier source="StreamKindID (MediaInfo)">0</essenceTrackIdentifier>
		<essenceTrackEncoding version="Version 1.0" annotation="endianness:Little compression_mode:Lossless">DPX</essenceTrackEncoding>
		<essenceTrackDataRate unitsOfMeasure="bit/second">15539824</essenceTrackDataRate>
		<essenceTrackFrameRate annotation="interlacement:Progressive">25.000</essenceTrackFrameRate>
		<essenceTrackBitDepth>8</essenceTrackBitDepth>
		<essenceTrackFrameSize>176x144</essenceTrackFrameSize>
		<essenceTrackAspectRatio>1.222</essenceTrackAspectRatio>
		<essenceTrackTimeStart annotation="">00:00:00.042</essenceTrackTimeStart>
		<essenceTrackDuration>00:00:01:00</essenceTrackDuration>
		<essenceTrackAnnotation annotationType="Format_Compression">Raw</essenceTrackAnnotation>
		<essenceTrackAnnotation annotationType="Format_Settings_Packing">Packed</essenceTrackAnnotation>
		<essenceTrackAnnotation annotationType="MuxingMode">DPX</essenceTrackAnnotation>
		<essenceTrackAnnotation annotationType="FrameCount">25</essenceTrackAnnotation>
		<essenceTrackAnnotation annotationType="ColorSpace">RGB</essenceTrackAnnotation>
		<essenceTrackAnnotation annotationType="StreamSize">1942400</essenceTrackAnnotation>
		<essenceTrackAnnotation annotationType="colour_description_present">Yes</essenceTrackAnnotation>
		<essenceTrackAnnotation annotationType="colour_primaries">Linear</essenceTrackAnnotation>
		<essenceTrackAnnotation annotationType="Source">dpx\title-of-work_00000001.dpx</essenceTrackAnnotation>
		<essenceTrackAnnotation annotationType="Source_Last">dpx\title-of-work_00000025.dpx</essenceTrackAnnotation>
	</instantiationEssenceTrack>
	<instantiationEssenceTrack>
		<essenceTrackType>Audio</essenceTrackType>
		<essenceTrackIdentifier source="ID" />
		<essenceTrackIdentifier source="StreamKindID (MediaInfo)">0</essenceTrackIdentifier>
		<essenceTrackEncoding source="codecid" ref="1" annotation="endianness:Little signedness:Signed">PCM</essenceTrackEncoding>
		<essenceTrackDataRate unitsOfMeasure="bit/second" annotation="CBR">705600</essenceTrackDataRate>
		<essenceTrackSamplingRate unitsOfMeasure="Hz">44100</essenceTrackSamplingRate>
		<essenceTrackBitDepth>16</essenceTrackBitDepth>
		<essenceTrackDuration>00:00:01.000</essenceTrackDuration>
		<essenceTrackAnnotation annotationType="MuxingMode">Wave</essenceTrackAnnotation>
		<essenceTrackAnnotation annotationType="SamplingCount">44100</essenceTrackAnnotation>
		<essenceTrackAnnotation annotationType="StreamSize">88200</essenceTrackAnnotation>
		<essenceTrackAnnotation annotationType="Encoded_Application">Lavf58.17.103</essenceTrackAnnotation>
		<essenceTrackAnnotation annotationType="Source">title-of-work.wav</essenceTrackAnnotation>
	</instantiationEssenceTrack>
	<instantiationAnnotation annotationType="FrameCount">25</instantiationAnnotation>
	<instantiationAnnotation annotationType="File_Created_Date">UTC 2018-08-30 12:21:43.691</instantiationAnnotation>
	<instantiationAnnotation annotationType="File_Created_Date_Local">2018-08-30 14:21:43.691</instantiationAnnotation>
</pbcoreInstantiationDocument>
```

**Comment by kieranjol** [comment]
Very lovely :)

**Pull request merged**
