### PR TITLE
Fixed equality comparison that must be an assignment.

### PR DESCRIPTION
**Pull request by diegocr**
Summary says it all.

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Oops... Thanks for catching that!

**Comment by diegocr** [comment]
Hi @JeromeMartinez, np! I'm building the library using Emscripten and it did thrown a few warnings which allowed me to catch :)

Btw, if you don't mind, could you please take a look at https://github.com/buzz/mediainfo.js/issues/14? perhaps you have some idea, which will be greatly appreciated since i'm really stuck on that issue with `Open_Buffer_Continue`

**Comment by JeromeMartinez** [comment]
Planned but more complicated, longer to analyse, and I need some rest.
I did not care enough about a JS version of MediaInfo and I am very interested in having a stable version of it.

**Comment by diegocr** [comment]
Ok, no problem, was just curious if you might be aware of some issue with `Open_Buffer_Continue` in 17.10 or it's just something of Emscripten, although a previous version did seem to work fine as available on that mediainfo.js repo - thanks in any case.

**Pull request merged**
