### PR TITLE
Fix include

### PR DESCRIPTION
**Pull request by pavel-pimenov**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
" 	Missing #include "MediaInfo/PreComp.h" and #pragma hdrstop"
I prefer not too touch to thirdparty code, and the precomp is not useful for these files.
please remove this commit.

**Comment by JeromeMartinez** [comment]
there is an add then a remove. Better to just remove the commit.

**Comment by pavel-pimenov** [comment]
git reset --hard 153a8bd692f7bdf0ebbb0f9172ff4676265e6635 ?

**Comment by JeromeMartinez** [comment]
I don't know the command, I use an UI (TortoiseGit), I am not an expert, I use to save the last patch, "revert" to the first patch, then apply the last patch (so the middle patch is no more there).
Or store the 2 patches I want, use another branch an apply the 2 patches only.

**Comment by pavel-pimenov** [comment]
ok

**Comment by pavel-pimenov** [comment]
https://github.com/MediaArea/MediaInfoLib/pull/333

**Pull request closed without merging**
