### PR TITLE
Update parameter definitions

### PR DESCRIPTION
**Pull request by ablwr**
This PR is for filling out and clarifying values in MediaInfo's `--Info-Parameters` page. 

Now ready for review!

### CODE REVIEW

**Comment by ablwr** [comment]
I have been moving through these parameters (more than what is in this PR currently) and am trying to keep questions to a minimum, but I still have a few meta-questions. Can you tell me if these assumptions are correct?

1. `Count`, `Status`, and `Inform` all seem like they are primarily used for internal purposes, is that true?

2. For the syntax between the name and definition, the pattern like "N YTY", I am assuming Letter[0] is Y for default display, N for not (only show on `-f`), then a space, and then another string. I'm assuming T for Text, I for Integer, F for Float, and the extra Ys and Ns are whether to show the field at all if there's no value. Is that kinda right?


3. "Original" is used to mean the data coming from the codec and not the container, right?

4. I found the definition and meaning of "Source" [on Sourceforge](https://sourceforge.net/p/mediainfo/feature-requests/366/#f4cf), but does that apply to new fields (that don't seem to be in use) like `MasteringDisplay_ColorPrimaries_Source`? What do you mean when you use "Source"?

5. What is your definition of "Nominal" for bit rates and frame rates? I am working with some competing definitions more broadly.

**Comment by ablwr** [comment]
Something else I cannot figure out in the Video section is the meaning of these four fields:
`Stored_Width,  Stored_Height and `Sampled_Width, Sampled_Height`? They don't have any current definitions and it's not clear from looking at the code or other resources.

**Comment by ablwr** [comment]
:innocent:

**Comment by JeromeMartinez** [comment]
sorry about the delay, it is a lot to review... And still late on hot stuff.
I don't forget!

**Comment by ablwr** [comment]
Is this still blocked?

**Comment by JeromeMartinez** [comment]
Super long delay but it will be merged soon!
Rebased, slightly edited.

**Comment by ablwr** [comment]
WOW!!!!!!!!!!!!!!!!!! :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada:

**Comment by ablwr** [comment]
Thank you, this is great! Can't wait to check it out in the next release!!!!

**Comment by JeromeMartinez** [comment]
> Can't wait to check it out in the next release!!!!

hmmm... Yes and no. It will be in the next release in the source code, but the binary delivery [will be without the descriptions](https://github.com/MediaArea/MediaInfoLib/pull/1712) (there will be a hint for checking the official repo at https://github.com/MediaArea/MediaInfoLib/tree/master/Source/Resource/Text/Stream , the idea is not to hide the description).

We are working on reducing the binary size, especially for the JavaScript and the Amazon Lambda targets, bigger binary means slower loading time, and theses additions were inflating the binary size much (not a criticism, it is good to have theses descriptions).

**Comment by ablwr** [comment]
Ahh got it, I saw those PRs come in earlier today. That's good. 

Are there plans to display params in a UX-friendlier way on the MediaArea site?

**Comment by JeromeMartinez** [comment]
> Are there plans to display params in a UX-friendlier way on the MediaArea site?

We should definitely do that for more visibility, something similar to https://mediaarea.net/en/MediaInfo/Support/Tags, but we are so laaaaate on website update (the page I linked is so old, need a big refresh).
Please add a ticket on https://github.com/MediaArea/MediaArea-Website/issues for tracking that.

**Pull request merged**
