### PR TITLE
Reduce the count of map::operator[key] call

### PR DESCRIPTION
**Pull request by pavel-pimenov**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Will not work with some defines (e.g. for the first one if MEDIAINFO_PCM_NO)
I propose to do the assignment earlier (e.g. for the first one before SMPTE ST 337 part so the "Stream[Stream_ID].Parsers.push_back(Parser);" in the SMPTE ST 337 can also be changed) so we avoid risks with the defines. to do for all parts.

**Comment by pavel-pimenov** [comment]
Thank you

**Comment by pavel-pimenov** [comment]
Help backtrace ?

ulimit -c unlimited

ppa@dht:~/src/MediaInfoLib/Project/GNU/Library$ ./autogen.sh && ./configure --with-libcurl --enable-debug --enable-staticlibs && make -B


ppa@dht:~/src/MediaInfoLib/Project/GNU/Library$ make clone_regression_files && make check
make: Nothing to be done for `clone_regression_files'.
Making check in .
make[1]: Entering directory `/home/ppa/src/MediaInfoLib/Project/GNU/Library'
make[1]: Nothing to be done for `check-am'.
make[1]: Leaving directory `/home/ppa/src/MediaInfoLib/Project/GNU/Library'
Making check in test
make[1]: Entering directory `/home/ppa/src/MediaInfoLib/Project/GNU/Library/test'
make  mil_analyze
make[2]: Entering directory `/home/ppa/src/MediaInfoLib/Project/GNU/Library/test'
make[2]: `mil_analyze' is up to date.
make[2]: Leaving directory `/home/ppa/src/MediaInfoLib/Project/GNU/Library/test'
make  check-TESTS
make[2]: Entering directory `/home/ppa/src/MediaInfoLib/Project/GNU/Library/test'
make[3]: Entering directory `/home/ppa/src/MediaInfoLib/Project/GNU/Library/test'
FAIL: trace.sh
SKIP: s3.sh
make[4]: Entering directory `/home/ppa/src/MediaInfoLib/Project/GNU/Library/test'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/home/ppa/src/MediaInfoLib/Project/GNU/Library/test'
============================================================================
Testsuite summary for libmediainfo 0.7.89
============================================================================
# TOTAL: 2
# PASS:  0
# SKIP:  1
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See test/test-suite.log
============================================================================

ppa@dht:~/src/MediaInfoLib/Project/GNU/Library/test$ gdb -c core
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
[New LWP 12339]
Core was generated by `/home/ppa/src/MediaInfoLib/Project/GNU/Library/test/.libs/lt-mil_analyze -d -h'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x40a597a1 in ?? ()
(gdb) bt
#0  0x40a597a1 in ?? ()
#1  0xbf828814 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)

**Comment by JeromeMartinez** [comment]
Not sure about the origin of the failed check, let's modify first the commit in order to support all "define" combination then I check the trace.sh issue if still there.

**Comment by JeromeMartinez** [comment]
@g-maxime can you provide more info about the reason trace.sh fails?

**Comment by pavel-pimenov** [comment]
My bug
Reproduced crash  VC++2015

 	msvcp140d.dll!std::_Debug_message(const wchar_t * message, const wchar_t * file, unsigned int line) Line 17	C++
 	MediaInfo.dll!std::vector<MediaInfoLib::File__Analyze *,std::allocator<MediaInfoLib::File__Analyze *> >::operator[](unsigned int _Pos) Line 1234	C++
>	MediaInfo.dll!MediaInfoLib::File_Riff::AVI__hdlr_strl_strf_auds() Line 1394	C++
 	MediaInfo.dll!MediaInfoLib::File_Riff::AVI__hdlr_strl_strf() Line 1192	C++
 	MediaInfo.dll!MediaInfoLib::File_Riff::Data_Parse() Line 453	C++
 	MediaInfo.dll!MediaInfoLib::File__Analyze::Data_Manage() Line 2364	C++
 	MediaInfo.dll!MediaInfoLib::File__Analyze::Buffer_Parse() Line 1524	C++
 	MediaInfo.dll!MediaInfoLib::File__Analyze::Open_Buffer_Continue_Loop() Line 1099	C++
 	MediaInfo.dll!MediaInfoLib::File__Analyze::Open_Buffer_Continue(const unsigned char * ToAdd, unsigned int ToAdd_Size) Line 670	C++

**Pull request merged**
