### PR TITLE
Added static library build using qmake for MacOSX with clang and fixe…

### PR DESCRIPTION
**Pull request by rokrau**
…d a few small compiler warnings and problems

### CODE REVIEW

**Comment by githubics** [comment]
Jerome, 
refreshing my pull request. This will now work with the MSVC compilers that we have tested with. 
Since I am publishing some work that uses this I would like to request the merge of the file into Contrib so that my users can build this as a static library with qmake. 
I will likely also make a bitbake layer to build MediaInfoLib with yocto for embedded devices soon.

**Comment by JeromeMartinez** [comment]
I would prefer something more generic than "for clang" (e.g. the -W stuff you put is clang specific), and I would like to put it in the official part (not in Contrib) and I am ready to maintain it. I put some changes (e.g. I prefer that the c++11 is not forced, I put the option in the ReadMe file).

Please review this branch:
https://github.com/JeromeMartinez/MediaInfoLib/tree/rokrau

> I will likely also make a bitbake layer to build MediaInfoLib with yocto for embedded devices soon. 

I take it! :)

**Comment by githubics** [comment]
Jerome.
Thanks and this looks very good to me.
Once it goes live I will change the links in my blogs and the build
instructions for my Media Manager to pull directly from your master
branches!

Very cool.
Thanks again

Roland

**Comment by JeromeMartinez** [comment]
Modified commits taken from https://github.com/MediaArea/MediaInfoLib/pull/150

Don't hesitate to send updates based on these new files.

**Pull request closed without merging**
