### PR TITLE
Complement to MediaInfo #124

### PR DESCRIPTION
**Pull request by Sami32**
Complement asked in https://github.com/MediaArea/MediaInfo/pull/124/files

@JeromeMartinez I'm a little confuse with OpenMG and ATRAC3...so i added them to the already exixting ones.

Should i have added an WTV entry ?
https://msdn.microsoft.com/en-us/library/windows/desktop/bb188788.aspx

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Looks fine.
For WTV, there is an issue because I don't detect them correctly. I'll add a basic detection of WTV in order to avoid the current false detection (I thought it was no more used so did not spend time on it).

**Comment by Sami32** [comment]
@JeromeMartinez As the latest Windows 10 don't have a Windows Media Center anymore, it'll happen.
https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0
That's said i never used/met it before my tests.

Thanks for your reviewing :)

**Comment by JeromeMartinez** [comment]
> Should i have added an WTV entry ?

[Added](https://github.com/MediaArea/MediaInfoLib/pull/389) with test of WTV (no more video stream displayed, just "WTV" format)

**Comment by Sami32** [comment]
That was fast ;)

**Pull request merged**
