### PR TITLE
Atrac fix attempt

### PR DESCRIPTION
**Pull request by Sami32**
See #898 and #908 

Not sure if it is the correct way to handle it or even if this change is correct but it just an attempt ;)

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Is fine.
Any idea about the difference between the 2 UUID (per format)?

**Comment by JeromeMartinez** [comment]
> Any idea about the difference between the 2 UUID (per format)?

Argh, actually my mistake, there is only one UUID, the older one is an UUID with inverted bytes, a mistake on my side and I fixed it some time ago (and I missed that the UUID is somewhere else, so the bug)

**Comment by Sami32** [comment]
Yes, the value has changed in MediaInfo somewhere after 7.99

**Comment by Sami32** [comment]
It is why i wasn't sure what way was correct to fix it.

**Pull request merged**
