### PR TITLE
PAC subtitle format support

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Close https://github.com/MediaArea/MediaInfoLib/issues/1945

### CODE REVIEW

**Comment by Odie3** [comment]
what is the ETA for this to be released in the MediaInfo GUI?

**Comment by Odie3** [comment]
Thanks @JeromeMartinez - works great on my desktop to look at PAC files.  Now if my guys can get this new feature built into our WB AWS App.

**Comment by JeromeMartinez** [comment]
> Now if my guys can get this new feature built into our WB AWS App.

FYI our [dev repo](https://mediaarea.net/download/snapshots/binary) contains the AWS lambda builds (lib and cli).

BTW, don't hesitate to say thanks to the sponsor of this feature, and [we can develop other features](https://mediaarea.net/Services) if you need some and if they are not already developed ;-).

**Comment by Odie3** [comment]
My guys found that and I am testing it now in AWS (its working as expected from the offline CLI results).

I am in the same company as the sponsor, just in a different department ;-)

Thank you for your very prompt help and that Dev Snapshot.

**Comment by Odie3** [comment]
Hi @JeromeMartinez - I am sure this is a bit annoying but might you be able to share the x32 version of MediaInfo.dll for this build too?

**Pull request merged**
