### PR TITLE
Remove URL parameters from FileName

### PR DESCRIPTION
**Pull request by g-maxime**
Signed-off-by: Maxime Gervais <gervais.maxime@gmail.com>

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
I think I prefer to use `Reader_libcurl_FileNameWithoutPassword()` everywhere (also in the error logs), possible to use it with the additional filter on "?"?

**Comment by g-maxime** [comment]
@JeromeMartinez I can chain the two functions call, or add a parameter to Reader_libcurl_FileNameWithoutPassword()

**Comment by JeromeMartinez** [comment]
add a parameter to Reader_libcurl_FileNameWithoutPassword(), I consider the part after ? as like a password (it is actually the case for AWS presigned URLs!).

**Comment by g-maxime** [comment]
So I delete the parameters also from the logs?

**Comment by JeromeMartinez** [comment]
Yes

**Pull request merged**
