### PR TITLE
Avoid crash in mxf assets on unsupported audio

### PR DESCRIPTION
**Pull request by aipsvrr**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Could you share a file demonstrating this issue?

**Comment by aipsvrr** [comment]
Hi @JeromeMartinez ,
I need some time to get an asset (will try update later on if you would still want to have that).
But for now, I'd like to add some details :)
Here is a crash stack:
`Program terminated with signal 11, Segmentation fault.
#0  0x00007daf6a1e579f in MediaInfoLib::File_ChannelSplitting::Read_Buffer_Continue() () from /lib64/libmediainfo.so.0
#1  0x00007daf6a08fb2e in MediaInfoLib::File__Analyze::Open_Buffer_Continue_Loop() () from /lib64/libmediainfo.so.0
#2  0x00007daf6a090468 in MediaInfoLib::File__Analyze::Open_Buffer_Continue(unsigned char const*, unsigned long) () from /lib64/libmediainfo.so.0
#3  0x00007daf6a091f44 in MediaInfoLib::File__Analyze::Open_Buffer_Continue(MediaInfoLib::File__Analyze*, unsigned char const*, unsigned long, bool, double) () from /lib64/libmediainfo.so.0
#4  0x00007daf6a56c827 in MediaInfoLib::File_Mxf::Data_Parse() () from /lib64/libmediainfo.so.0
#5  0x00007daf6a08b1e7 in MediaInfoLib::File__Analyze::Data_Manage() () from /lib64/libmediainfo.so.0
#6  0x00007daf6a08fa58 in MediaInfoLib::File__Analyze::Buffer_Parse() () from /lib64/libmediainfo.so.0
#7  0x00007daf6a08fbf8 in MediaInfoLib::File__Analyze::Open_Buffer_Continue_Loop() () from /lib64/libmediainfo.so.0
#8  0x00007daf6a090468 in MediaInfoLib::File__Analyze::Open_Buffer_Continue(unsigned char const*, unsigned long) () from /lib64/libmediainfo.so.0
#9  0x00007daf6a141193 in MediaInfoLib::MediaInfo_Internal::Open_Buffer_Continue(unsigned char const*, unsigned long) () from /lib64/libmediainfo.so.0
#10 0x00007daf6a5ceb41 in MediaInfoLib::Reader_File::Format_Test_PerParser_Continue(MediaInfoLib::MediaInfo_Internal*) () from /lib64/libmediainfo.so.0
#11 0x00007daf6a5cd7a2 in MediaInfoLib::Reader_File::Format_Test_PerParser(MediaInfoLib::MediaInfo_Internal*, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&) () from /lib64/libmediainfo.so.0
#12 0x00007daf6a5cdf68 in MediaInfoLib::Reader_File::Format_Test(MediaInfoLib::MediaInfo_Internal*, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >) ()
   from /lib64/libmediainfo.so.0
#13 0x00007daf6a1530b2 in MediaInfoLib::MediaInfo_Internal::Entry() () from /lib64/libmediainfo.so.0
#14 0x00007daf6a14fa4c in MediaInfoLib::MediaInfo_Internal::Open(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&) () from /lib64/libmediainfo.so.0
#15 0x00007daf6a157f28 in MediaInfoLib::MediaInfoList_Internal::Entry() () from /lib64/libmediainfo.so.0
#16 0x00007daf6a15a8fa in MediaInfoLib::MediaInfoList_Internal::Open(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, MediaInfoLib::fileoptions_t) ()
   from /lib64/libmediainfo.so.0
#17 0x0000000000402d26 in main ()`

The reason of that SEGFAULT is that [`Common` is NULL](https://github.com/MediaArea/MediaInfoLib/blob/88f3ea4aa7218ab94386559dc51b100924263be9/Source/MediaInfo/Audio/File_ChannelSplitting.cpp#L267).
That happened because `Common` was not initialized in [`File_ChannelSplitting::Read_Buffer_Init()`](https://github.com/MediaArea/MediaInfoLib/blob/88f3ea4aa7218ab94386559dc51b100924263be9/Source/MediaInfo/Audio/File_ChannelSplitting.cpp#L204) method due to wrong `BitDepth` that was calculated as `1` [(`BitDepth=3*8/16`)](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Multiple/File_Mxf.cpp#L18676) because of improper `BlockAlign` value (BlockAlign=3 instead of 48) in WaveAudioEssenceDescriptor while `ChannelsCount` is 16 and `QuantizationBits` are 24.
Well, I'm pretty sure that BlockAlign value was wrong in my test asset (I see that similar problems were already observed and Descriptor was fixed before for [PCM parser](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Multiple/File_Mxf.cpp#L18745)). 
But mediainfo crash even on "non-well formed" file is not something that we don't expect :(

[Descriptor's (BlockAlign) Fix](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Multiple/File_Mxf.cpp#L18745)  was not working in my case because BlockAlign was fixed after [Parser->BitDepth](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Multiple/File_Mxf.cpp#L18676) was already calculated to `1` for ChannelSplitting parser. Btw, I tried to apply this fix [earlier in code](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Multiple/File_Mxf.cpp#L18668) and it works then.

By summarizing all above, two things were spotted:
1) Mediainfo can mitigate influence of potentially incorrect BlockAlign descriptor for its analysis but it depends on descriptor's sequence (if `ChooseParser_Pcm` would be called before `ChooseParser_ChannelSplitting` then no problems would be observed)
2) ChannelSplitting Parser can stay uninitialized if audio is not supported but still can be called and so segfault is possible in this case (no check on null pointer is performing in `Read_Buffer_Continue()`)

Hope you will find my description useful.
Thanks!

**Comment by aipsvrr** [comment]
Hi @JeromeMartinez ,
Returning back to you with approx. 8-seconds long asset's fragment (splitted by 3 parts: [crash_67662964_001.zip](https://github.com/user-attachments/files/16487210/crash_67662964_001.zip), [crash_67662964_002.zip](https://github.com/user-attachments/files/16487213/crash_67662964_002.zip), [crash_67662964_003.zip](https://github.com/user-attachments/files/16487215/crash_67662964_003.zip). Please check that md5sum of resulting file is: c15b109561ef9110ca4b4ed1b1c89937) demonstrating this issue.
Thanks!

**Comment by JeromeMartinez** [comment]
> But mediainfo crash even on "non-well formed" file is not something that we expect :(

We agree :)

> Btw, I tried to apply this fix [earlier in code](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Multiple/File_Mxf.cpp#L18668) and it works then.

I definitely need to refactor this code and avoid to rely much on `BlockAlign`, because the current code will not catch Dolby E in a file with wrong `BlockAlign`.

In the meantime, I take this "hot fix", thank you.

**Pull request merged**
