### PR TITLE
S_DVBSUB

### PR DESCRIPTION
**Pull request by Sami32**
https://github.com/Matroska-Org/matroska-specification/blob/dfaf1eb14cd2cdb628967a09c8bbdd630f5b6118/subtitles.md#digital-video-broadcasting-dvb-subtitles

This time, i've a sample :wink: 
[dvbtextualsubtitles.zip](https://github.com/MediaArea/MediaInfoLib/files/762067/dvbtextualsubtitles.zip)

As a side note, _**TVheadend**_ is able to produce it.
I've extracted it with [FFmpeg](https://git.ffmpeg.org/gitweb/ffmpeg.git/blobdiff/e87a4a85c11e348be8682acf39573fd2c5e22193..dface53497c3531da101b2872df301acca313142:/libavformat/matroska.c).

**EDIT**: I should have mentioned that _**mkvmerge**_ is able to produce it since 9.8.0.
As do _**TSDoctor**_ and _**VideoRedoSuite**_, commercial softwares having a free trial.

### CODE REVIEW

**Comment by Sami32** [comment]
It' was a laborious Git handling, but i think i'm done for this PR now ;)

**Comment by JeromeMartinez** [comment]
FYI codecs.csv update is not necessary, it is used for legacy purposes only (should go away soon).

**Comment by Sami32** [comment]
@JeromeMartinez Thank you for you approval :-)

**Comment by JeromeMartinez** [comment]
Actually the opposite: you are the one who contributes ;-).
Don't hesitate to send new PRs.

**Pull request merged**
