### PR TITLE
MPEG-4: ProRes RAW support

### LINKED ISSUE #1008: ProRes RAW
It seem that for now it show the codecID as format: `aprh`
Shouldn't "ProRes RAW" be more meaningful?

Samples:
https://filmplusgear.com/prores-raw-testfiles-for-download-nab-2018/

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Fix #1008.

Looks like there are [2 flavors or RAW (RAW and RAW HQ)](https://www.premiumbeat.com/blog/prores-raw-change-your-work/), @retokromer any idea if `aprh` 4CC is for RAW or RAW HQ (or both)?

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
From https://forum.blackmagicdesign.com/viewtopic.php?f=2&t=71762&start=50#p402542, now trying to bet with aprh for "RAW HQ" and aprn for "RAW".

**Comment by retokromer** [comment]
As long as I know aprh = RAW HQ and aprn = RAW.

**Comment by retokromer** [comment]
>As long as I know aprh = RAW HQ and aprn = RAW.

Yes, I confirm, the files I have seen so far are that way. I don’t have seen yet any `aprx`, `aprs` or `apro`, mentioned in the referenced Blackmagic Forum.

**Comment by retokromer** [comment]
Yes, I guess it’s the way to go.

**Comment by retokromer** [comment]
For référence RAW and RAW HQ are mentioned [here](https://images.apple.com/final-cut-pro/docs/Apple_ProRes_RAW_White_Paper.pdf) but not the others.

**Pull request merged**
