### PR TITLE
MP4 Disable Track and Alternate Group

### PR DESCRIPTION
**Pull request by ndjamena**
I'm not sure how you want to handle these kind of things.

You'll have to add the Matroska Enabled flag too at some point and there's already a "default" and "forced" field, it's useful to know, but I'm worried about cluttering the output.

MPC-HC obeys the Matroska enabled flag, I don't know how many others do.

For MP4 MP4Box only shows the enabled flag if it's set to disabled, and as far as the MP4 specs are concerned, having an alternate group of zero means the track doesn't have an alternate group.

I don't know if there's a way of specifying to only show a field in output if it contains or doesn't contain a certain value.  To be honest, I don't see the point in showing the Matroska forced flag for audio and video, unless it happens to be set to yes.  I'm not even sure what that would mean in the real world.

### CODE REVIEW

**Comment by ndjamena** [comment]
What did I do wrong this time!

**Comment by JeromeMartinez** [comment]
I think you forgot to rebase before doing the PR, so there is code between your fork and now.

**Comment by ndjamena** [comment]
I have no idea what's happening in the comments.  I think they may be weird unicode characters.

**Comment by JeromeMartinez** [comment]
good to remove Unicode chars in source code

**Comment by ndjamena** [comment]
https://developer.apple.com/library/mac/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html

>The video track’s Alternate Group ID is 0, which means that it is not in an alternate group


****MP4Box Output***
```
* Movie Info *
        Timescale 600 - Duration 02:21:38.373
        12 track(s)
        Fragmented File: no
        File suitable for progressive download (moov before mdat)
        File Brand M4V  - version 0
        Created: GMT Fri Oct 02 21:24:03 2015
        Modified: GMT Fri Oct 02 21:24:34 2015

File has no MPEG4 IOD/OD

iTunes Info:
        Name: Avengers: Age of Ultron
        Artist: Joss Whedon
        Genre: Sci-Fi & Fantasy
        Compilation: No
        Gapless album: No
        Created: 2015-05-01T07:00:00Z
        Cover Art: JPEG File
1 UDTA types: meta (1)

Track # 1 Info - TrackID 2 - TimeScale 48000 - Media Duration 02:21:17.397
Track has 1 edit lists: track duration is 02:21:17.343
Media Info: Language "English (en-US)" - Type "soun:mp4a" - 397378 samples
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC - 2 Channel(s) - SampleRate 48000
Self-synchronized
Alternate Group ID 1

Track # 2 Info - TrackID 1 - TimeScale 2997 - Media Duration 02:21:38.373
Track has 1 edit lists: track duration is 02:21:38.373
Media Info: Language "en (en)" - Type "vide:avc1" - 203757 samples
Visual Track layout: x=0 y=0 width=1916 height=800
MPEG-4 Config: Visual Stream - ObjectTypeIndication 0x21
AVC/H264 Video - Visual Size 1916 x 800
        AVC Info: 1 SPS - 1 PPS - Profile High @ Level 4
        NAL Unit length bits: 32
        Pixel Aspect Ratio 1:1 - Indicated track size 1916 x 800
Synchronized on stream 2

Track # 3 Info - TrackID 3 - TimeScale 2997 - Media Duration 02:21:06.883
Track has 1 edit lists: track duration is 02:21:06.883
Media Info: Language "Spanish; Castilian (es-419)" - Type "sbtl:tx3g" - 20 samples
Unknown Text Stream
 Size 1916 x 120 - Translation X=0 Y=680 - Layer 0
Alternate Group ID 2

Track # 4 Info - TrackID 4 - TimeScale 30000 - Media Duration 02:13:29.401
Track has 1 edit lists: track duration is 02:13:29.400
Media Info: Language "English (en-US)" - Type "clcp:c608" - 3115 samples
Unknown media type

Track # 5 Info - TrackID 5 - TimeScale 2997 - Media Duration 02:21:06.883
Track has 1 edit lists: track duration is 02:21:06.883
Track is disabled
Media Info: Language "Spanish; Castilian (es-419)" - Type "sbtl:tx3g" - 3756 samples
Unknown Text Stream
 Size 1916 x 120 - Translation X=0 Y=680 - Layer 0
Alternate Group ID 2

Track # 6 Info - TrackID 6 - TimeScale 2997 - Media Duration 02:13:29.384
Track has 1 edit lists: track duration is 02:13:29.383
Track is disabled
Media Info: Language "English (en-US)" - Type "sbtl:tx3g" - 3712 samples
Unknown Text Stream
 Size 1916 x 120 - Translation X=0 Y=680 - Layer 0
Alternate Group ID 2

Track # 7 Info - TrackID 7 - TimeScale 2997 - Media Duration 02:21:06.800
Track has 1 edit lists: track duration is 02:21:06.800
Track is disabled
Media Info: Language "French (fr-CA)" - Type "sbtl:tx3g" - 3768 samples
Unknown Text Stream
 Size 1916 x 120 - Translation X=0 Y=680 - Layer 0
Alternate Group ID 2

Track # 8 Info - TrackID 8 - TimeScale 2997 - Media Duration 02:21:06.758
Track has 1 edit lists: track duration is 02:21:06.758
Track is disabled
Media Info: Language "Portuguese (pt-BR)" - Type "sbtl:tx3g" - 3758 samples
Unknown Text Stream
 Size 1916 x 120 - Translation X=0 Y=680 - Layer 0
Alternate Group ID 2

Track # 9 Info - TrackID 9 - TimeScale 1000 - Media Duration 02:21:38.373
Track has 1 edit lists: track duration is 02:21:38.371
Track is disabled
Media Info: Language "English (en-US)" - Type "text:tx3g" - 14 samples
Unknown Text Stream
 Size 0 x 0 - Translation X=0 Y=0 - Layer 0

Track # 10 Info - TrackID 10 - TimeScale 1000 - Media Duration 02:21:38.373
Track has 1 edit lists: track duration is 02:21:38.371
Track is disabled
Media Info: Language "und (und)" - Type "vide:jpeg" - 14 samples
Visual Track layout: x=0 y=0 width=640 height=267
Visual Track - Compressor "" - Resolution 640 x 267

Track # 11 Info - TrackID 11 - TimeScale 48000 - Media Duration 02:21:17.344
Track has 1 edit lists: track duration is 02:21:17.343
Track is disabled
Media Info: Language "English (en-US)" - Type "soun:ac-3" - 264917 samples
        AC-3 stream - Sample Rate 48000 - 5.1 channel(s) - bitrate 192000
Alternate Group ID 1

Track # 12 Info - TrackID 12 - TimeScale 48000 - Media Duration 02:21:17.397
Track has 1 edit lists: track duration is 02:21:17.353
Track is disabled
Media Info: Language "Spanish; Castilian (es-419)" - Type "soun:mp4a" - 397378 samples
MPEG-4 Config: Audio Stream - ObjectTypeIndication 0x40
MPEG-4 Audio AAC LC - 2 Channel(s) - SampleRate 48000
Synchronized on stream 2
Alternate Group ID 1
```

They call it "Alternate Group ID" but apple just calls it "Alternate Group".  And they don't bother showing the enabled flag if it's on.

...  um, that second video track is actually images for the chapters...

Would you consider breaking each chapter up into multiple fields?  I don't see how Matroska or MP4 chapter information can be properly displayed otherwise.

**Comment by JeromeMartinez** [comment]
> ... um, that second video track is actually images for the chapters...

Ouch...

> Would you consider breaking each chapter up into multiple fields? I don't see how Matroska or MP4 chapter information can be properly displayed otherwise.

Please open a [ticket](https://github.com/MediaArea/MediaInfoLib/issues) with some ideas about what you would like to do.

**Comment by JeromeMartinez** [comment]
From specs:

"One track in the group must be enabled; that is , the Track Enabled flag must be set (0x0001) in its track header ( 'tkhd' ). 
All other tracks in the group must be disabled "

Looks like it is similar to "Default" field in Matroska, so I propose to change !Disabled to "Default", and show it only if Alternate Group is not 0.

**Comment by ndjamena** [comment]
That's not on the page I liked to, where did you read that?

What does it say about tracks that AREN'T part of a group?  From experience, if they're not in a group and you enable all of them, iTunes should play everything at the same time.  I don't know if they've changed that behaviour, but apparently that's how it's supposed to work.

And it's not exactly like the Matroska "default", you can have several groups containing audio, enable one from each group and iTunes should play all of the enabled audio streams at the same time.

Like I said when I made the feature request, it's both the default and forced flag.  If I put the normal subtitles in one group and the forced subtitles in another and enable one of the forced subtitles, the forced subtitles should continue displaying even if I select a subtitle from the other group.

**Comment by ndjamena** [comment]
OH....

```
The group must contain tracks of only one type; for example, only subtitle tracks or only sound tracks.

•All tracks of the same type must be in a single alternate group.

•One track in the group must be enabled; that is, the Track Enabled flag must be set (0x0001) in its track header ('tkhd').

•All other tracks in the group must be disabled

```

And apparently MP4 can have forced subtitles somehow:

```
 any available appropriate subtitle track should be enabled so that any forced subtitles in the track can be displayed
```

It's more complicated then I thought.

**Comment by JeromeMartinez** [comment]
> That's not on the page I linked to, where did you read that?

[PDF](https://developer.apple.com/library/mac/documentation/QuickTime/QTFF/qtff.pdf) page 60.

>  if they're not in a group and you enable all of them, iTunes should play everything at the same time. 

Logical (I have tons of pofessionnal files without Alternate Group, and each track is a single channel of a 7.1 audio program, so they must be played at the same time).
Now, I don't know enough in case of e.g. 2 stereo tracks (English, Spanish) with Enabled set.

> And it's not exactly like the Matroska "default", you can have several groups containing audio, enable one from each group and iTunes should play all of the enabled audio streams at the same time.

It is "just" more advanced than Matroska "default", which is a use case of QuickTime with one "Alternate group". There just may have more than one group in QuickTime. so the purpose is the same (the one to play by default), or do I understand wrongly? This is the reason I think to reuse the "Defualt" field (same purpose).

> And apparently MP4 can have forced subtitles somehow. It's more complicated then I thought.

Right. It would be interesting to fill the "Forced" MediaInfo field somehow from QuickTime files.

**Comment by ndjamena** [comment]
I'm not actually an expert on mp4, I was just converting my DVDs to play on my iPhone, anything with commentary tracks I made using MP4Box was making an awful racket, so I did a quick search, discovered the enabled and alternate group commands and that's about it.

I didn't watch the things, so I've deleted them all now.

This is interesting though.

This is another point about chapters.  Both Blu Ray and MP4 seem to have their own versions of "Ordered Chapters"  Blu Ray in the form of play lists, MP4 in the form of edit lists.  The way Matroska does it is just one way of doing it, and covering each method would require some real thought to the "menu" display.

Chapters can be either Playlists or Markers.  Ordered chapters are playlists.


Apparently 29.97 fps is a valid frame rate too...

I'd have to take an active interest in M4V to be of any real use here, and I can't think of a use I'd have for it...

Referencetypes are where the action is.  I wish Matroska had something like 'fall'.

**Comment by JeromeMartinez** [comment]
so I change !Disabled to "Default" now and we see when there is any interest for more metadata (forced, menu...) display later.

**Comment by ndjamena** [comment]
This is the full referencebox for an AC3 stream in an iTunes file.

```
<TrackReferenceBox>
<BoxInfo Size="36" Type="tref"/>
<fallTrackReferenceBox Tracks=" 2">
<BoxInfo Size="12" Type="fall"/>
</fallTrackReferenceBox>
<ChapterTrackReferenceBox Tracks=" 5 6">
<BoxInfo Size="16" Type="chap"/>
</ChapterTrackReferenceBox>
</TrackReferenceBox>
```

I'm assuming 'fall' means fallback and it's pointing at an aac track, so they're basically identical.

Maybe we could add a "same as" field or something.

**Comment by JeromeMartinez** [comment]
> Maybe we could add a "same as" field or something.

"FallBackTo" field would be OK, please another PR (+file)

**Pull request merged**
