### PR TITLE
ACELP typo correction

### PR DESCRIPTION
**Pull request by Sami32**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
You need to change the [resulting cpp file](https://github.com/MediaArea/MediaInfoLib/blob/4468063f90bdf485a2d43b9fe66878dc37b9a15a/Source/MediaInfo/MediaInfo_Config_Automatic.cpp#L3759) too.

**Comment by Sami32** [comment]
Yep...i did it too fast ;)
Thanks.

**Comment by JeromeMartinez** [comment]
> Do the VIDEO_DELAY value can have decimal numbers ?

Yes (I think I don't do it for the moment, but it is a possibility if/when I want to have precision more than the millisecond)

**Comment by Sami32** [comment]
Thank you :) It was for our parsing Regex string.

**Pull request merged**
