### PR TITLE
fla

### PR DESCRIPTION
**Pull request by Sami32**
Complement this [MediaInfo PR](https://github.com/MediaArea/MediaInfo/pull/252).

### CODE REVIEW

**Comment by Sami32** [comment]
I shouldn't have added VRO as a specific format, perhaps as MPEG-PS.
I've done that from memory and it seem that i cannot rely on it ;)
http://www.pixelbeat.org/docs/DVD-VR/
https://en.wikipedia.org/wiki/DVD-VR

**Comment by Sami32** [comment]
Shouldn't **DTS** be "Dedicated To Sound" instead of "Digital theater Sound"?
https://dts.com/
https://en.wikipedia.org/wiki/DTS_(sound_system)
https://ccm.net/contents/46-dts-dedicated-to-sound

**Comment by JeromeMartinez** [comment]
> Shouldn't DTS be Dedicated To Sound instead of "Digital Theater Sound"?

Marketing change ("formerly known as Digital Theater Systems, Inc."), I'll change it at some point.

**Comment by Sami32** [comment]
I asked because i was not sure you wanted me to add this change into this PR.
So, if you agree i could fix it here.

**Comment by JeromeMartinez** [comment]
of for changing DTS thing.

**Comment by Sami32** [comment]
Ok, so can i leave the DTS Wikipedia link or should i remove it?

**Comment by JeromeMartinez** [comment]
Superseeded by https://github.com/MediaArea/MediaInfoLib/pull/869.

**Pull request closed without merging**
