### PR TITLE
Fix delete for void* (undefined behavior)

### PR DESCRIPTION
**Pull request by pavel-pimenov**
http://www.viva64.com/en/w/V772/

### CODE REVIEW

**Comment by pavel-pimenov** [comment]
Replace ((void**)m)[xxх] -> m[xxx]  ?

**Comment by JeromeMartinez** [comment]
I am not convinced by putting all pointers in the class.
Looking at the code, looks like the .h should be:

    void**  m;

Wouldn't be enough?

**Comment by pavel-pimenov** [comment]
HashFunction_Max = 6
....
delete Hash; Hash=new HashWrapper(Config->File_Hash_Get().to_ulong());
...
double heap-allocations.
imho overhead?

**Comment by JeromeMartinez** [comment]
> double heap-allocations.
imho overhead?

I don't understand, which overhead?

**Comment by pavel-pimenov** [comment]
Small test:
https://github.com/pavel-pimenov/sandbox/commit/fe44eeb303d50ef9bf0673253e29e85f33a2b551

Q:\git\sandbox\console-test\memory>calc-ram.exe 1
RAM before = 2142208
RAM after= 7413760 Delta = 5271552 Type =  m[i] = new A1

Q:\git\sandbox\console-test\memory>calc-ram.exe 2
RAM before = 2109440
RAM after= 5783552 Delta = 3674112 Type =  m[i] = new A2

**Comment by pavel-pimenov** [comment]
Close PR?

**Comment by JeromeMartinez** [comment]
no close, I am just late on reviewing.

**Pull request closed without merging**
