### PR TITLE
DV: width/height/chroma when stype is 1

### PR DESCRIPTION
**Pull request by JeromeMartinez**
Suggestion for https://github.com/mipops/dvrescue/issues/290, while finding a better way.

### CODE REVIEW

**Comment by dericed** [comment]
could you confirm the output for 
[test.dv.zip](https://github.com/MediaArea/MediaInfoLib/files/6641531/test.dv.zip)

**Comment by dericed** [comment]
I'd also like to test this against http://samples.ffmpeg.org/ffmpeg-bugs/roundup/issue1407/dv_dsf_1_stype_1.dv, but I suggest we merge and I'll test in the daily build.

**Comment by dericed** [comment]
Thanks, can you bump an update at https://mediaarea.net/download/snapshots/binary/dvrescue/.

**Comment by JeromeMartinez** [comment]
Latest build should be fine.Sent from my smartphone.
-------- Message d'origine --------De : Dave Rice ***@***.***> Date : 18/06/2021  17:57  (GMT+01:00) À : MediaArea/MediaInfoLib ***@***.***> Cc : Jérôme Martinez ***@***.***>, State change ***@***.***> Objet : Re: [MediaArea/MediaInfoLib] DV: width/height/chroma when stype is 1 (#1394) 
Thanks, can you bump an update at https://mediaarea.net/download/snapshots/binary/dvrescue/.

**Pull request merged**
