### PR TITLE
S_KATE

### PR DESCRIPTION
**Pull request by Sami32**
https://github.com/Matroska-Org/matroska-specification/blob/a2de2b67338fc6f5f64d58e0a65df88850eaca76/codec_specs.md

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
would you mind to share a sample file?

**Comment by Sami32** [comment]
@JeromeMartinez Sorry, i've just done it from specifications. I don't have such sample.

BTW, do you know what's happen with my anterior commit ?
I'm not able to find any trace of it...

**Comment by JeromeMartinez** [comment]
No problem.
For "anterior commit", I only saw PR on the MediaInfo repo (not MediaInfoLib), still pending.

**Comment by Sami32** [comment]
@JeromeMartinez OUPS...my bad, i forgotten that i was on MediaInfoLib :flushed:

**Comment by Sami32** [comment]
Finally, i'm on the slow way to domesticate Git ;)

**Comment by JeromeMartinez** [comment]
> i'm on the slow way to domesticate Git ;)

Same for me, no worries

**Comment by Sami32** [comment]
@JeromeMartinez Thanks ;) I use Tortoise Git.

After having read [that](https://wiki.xiph.org/OggKate), I finally found some KATE samples for our test collection :wink: 
http://people.xiph.org/~oggk/elephants_dream/elephantsdream-with-subtitles.ogg
https://ftp.gnu.org/video/Stephen_Fry-Happy_Birthday_GNU-nq_600px_425kbit.ogv

**Pull request merged**
