### PR TITLE
Added m4v default, forced and references values.

### PR DESCRIPTION
**Pull request by ndjamena**
I doubt this is the final product, but it's a start.

### CODE REVIEW

**Comment by ndjamena** [comment]
I did SOMETHING wrong again, and this time I'm stumped.

It compiles under Debug but not under Release.

It keeps complaining that "Flags" is undefined.  Apparently Skip_Flags and Get_Flags have different ways of accessing things depending on the settings.  I have noooo idea how the hell to fix that.

I don't know how to get a file to you, I think you put a password on the server to stop me uploading crap onto it, and I'm not putting iTunes files on MediaFire.

But this is what the output looks like:

```
General
Complete name                            : Z:\Transformers_ Age of Extinction.m4v
Format                                   : MPEG-4
Codec ID                                 : M4V  (M4V /mp42/isom)
File size                                : 6.18 GiB
Duration                                 : 2h 45mn
Overall bit rate mode                    : Variable
Overall bit rate                         : 5 343 Kbps
Movie name                               : Transformers: Age of Extinction
Performer                                : Michael Bay
Performer/Sorted by                      : Michael Bay
Director                                 : Michael Bay
Actor                                    : Mark Wahlberg / Stanley Tucci / John Goodman / Kelsey Grammer / 李冰冰 / T.J. Miller / Sophia Myles / Nicola Peltz / Jack Reynor
Screenplay by                            : Ehren Kruger
Producer                                 : Don Murphy / Tom DeSanto / Lorenzo di Bonaventura / Ian Bryce
Production studio                        : di Bonaventura Pictures
Genre                                    : Action & Adventure
ContentType                              : Short Film
Description                              : TRANSFORMERS: AGE OF EXTINCTION is the fourth film in director Michael Bay's global blockbuster
Recorded date                            : UTC 2014-06-27 07:00:00
Encoded date                             : UTC 2015-08-21 19:04:30
Tagged date                              : UTC 2015-08-21 19:05:34
Writing library                          : Apple QuickTime
Copyright                                : © 2014 Paramount Pictures Corporation. All Rights Reserved.
Cover                                    : Yes
Rating                                   : None
AppleStoreAccount                        : Muffins@evil.inc
AppleStoreCatalogID                      : 887735929
GenreID                                  : 4401
AppleStoreCountry                        : Zimbabwe
PurchaseDate                             : 1666-06-06 06:06:06
Title/Sort                               : Transformers: Age of Extinction
Vendor                                   : Paramount:vendor_id:35883NA001
Flavour                                  : 6:16p
ContentRating                            : us-movie|R|660|
LongDescription                          : From director Michael Bay and executive producer Steven Spielberg comes the best 'Transformers' ever! With humanity facing extinction from a terrifying new threat, it's up to Optimus Prime and the Autobots to save the world. But now that our government has turned against them, they'll need a new team of allies, including inventor Cade Yeager (Mark Wahlberg) and the fearsome Dinobots!
copy-warning                             : &nbsp;

Video #1
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 5 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 2h 45mn
Bit rate                                 : 4 634 Kbps
Width                                    : 1 912 pixels
Height                                   : 796 pixels
Display aspect ratio                     : 2.40:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (23976/1000) fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.127
Stream size                              : 5.36 GiB (87%)
Title                                    : Core Media Video
Language                                 : English
Default                                  : Yes
Encoded date                             : UTC 2015-08-21 19:04:30
Tagged date                              : UTC 2015-08-21 19:05:34
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Video #2
ID                                       : 10
Format                                   : JPEG
Codec ID                                 : jpeg
Duration                                 : 2h 45mn
Bit rate mode                            : Variable
Bit rate                                 : 3 721 bps
Width                                    : 640 pixels
Height                                   : 265 pixels
Display aspect ratio                     : 1.85:1
Frame rate mode                          : Variable
Frame rate                               : 0.002 fps
Minimum frame rate                       : 0.002 fps
Maximum frame rate                       : 0.003 fps
Color space                              : YUV
Chroma subsampling                       : 4:4:4
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 10.970
Stream size                              : 4.88 MiB (0%)
Title                                    : Core Media Video
Default                                  : No
Encoded date                             : UTC 2015-08-21 19:04:30
Tagged date                              : UTC 2015-08-21 19:05:34

Audio #1
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 2h 45mn
Source duration                          : 2h 45mn
Bit rate mode                            : Variable
Bit rate                                 : 160 Kbps
Maximum bit rate                         : 250 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 46.875 fps (1024 spf)
Compression mode                         : Lossy
Stream size                              : 185 MiB (3%)
Source stream size                       : 185 MiB (3%)
Title                                    : Core Media Audio
Language                                 : English
Default                                  : Yes
Encoded date                             : UTC 2015-08-21 19:04:30
Tagged date                              : UTC 2015-08-21 19:05:34
Alternate Group                          : 2
Menus                                    : 9,10
Fallback From                            : 11
Subtitles                                : 3

Audio #2
ID                                       : 11
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : ac-3
Duration                                 : 2h 45mn
Bit rate mode                            : Constant
Bit rate                                 : 384 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Frame rate                               : 31.250 fps (1536 spf)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 453 MiB (7%)
Title                                    : Core Media Audio
Language                                 : English
Default                                  : Inherited From: 2
Encoded date                             : UTC 2015-08-21 19:04:30
Tagged date                              : UTC 2015-08-21 19:05:34
Alternate Group                          : 2
Menus                                    : 9,10
Fallback To                              : 2
Subtitles                                : 3

Audio #3
ID                                       : 12
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 2h 45mn
Source duration                          : 2h 45mn
Bit rate mode                            : Variable
Bit rate                                 : 160 Kbps
Maximum bit rate                         : 245 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 46.875 fps (1024 spf)
Compression mode                         : Lossy
Stream size                              : 187 MiB (3%)
Source stream size                       : 187 MiB (3%)
Title                                    : Core Media Audio
Language                                 : Spanish
Default                                  : No
Encoded date                             : UTC 2015-08-21 19:04:30
Tagged date                              : UTC 2015-08-21 19:05:34
Alternate Group                          : 2
Menus                                    : 9,10
Subtitles                                : 5

Text #1
ID                                       : 3
Format                                   : Timed Text
Muxing mode                              : sbtl
Codec ID                                 : tx3g
Duration                                 : 1s 0ms
Bit rate                                 : 264 bps
Stream size                              : 33.0 Bytes (0%)
Title                                    : Core Media Subtitle
Language                                 : English
Default                                  : Yes
Forced                                   : Yes
Encoded date                             : UTC 2015-08-21 19:04:30
Tagged date                              : UTC 2015-08-21 19:05:34
Alternate Group                          : 1
Subtitles For                            : 2,11

Text #2
ID                                       : 4-CC1
Format                                   : EIA-608
Muxing mode                              : Final Cut
Codec ID                                 : c608
Duration                                 : 2h 37mn
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)
Title                                    : Core Media Closed Caption
Language                                 : English
Default                                  : Yes
Forced                                   : No
Encoded date                             : UTC 2015-08-21 19:04:30
Tagged date                              : UTC 2015-08-21 19:05:34

Text #3
ID                                       : 5
Format                                   : Timed Text
Muxing mode                              : sbtl
Codec ID                                 : tx3g
Duration                                 : 2h 23mn
Bit rate mode                            : Variable
Bit rate                                 : 1 bps
Stream size                              : 1.48 KiB (0%)
Title                                    : Core Media Subtitle
Language                                 : Spanish
Default                                  : No
Forced                                   : Yes
Encoded date                             : UTC 2015-08-21 19:04:30
Tagged date                              : UTC 2015-08-21 19:05:34
Alternate Group                          : 1
Subtitles For                            : 12
Full Alternative                         : 6

Text #4
ID                                       : 6
Format                                   : Timed Text
Muxing mode                              : sbtl
Codec ID                                 : tx3g
Duration                                 : 2h 38mn
Bit rate mode                            : Variable
Bit rate                                 : 92 bps
Stream size                              : 106 KiB (0%)
Title                                    : Core Media Subtitle
Language                                 : Spanish
Default                                  : No
Forced                                   : No
Encoded date                             : UTC 2015-08-21 19:04:30
Tagged date                              : UTC 2015-08-21 19:05:34
Alternate Group                          : 1
Subtitles For                            : 12
Forced Alternative                       : 5

Text #5
ID                                       : 7
Format                                   : Timed Text
Muxing mode                              : sbtl
Codec ID                                 : tx3g
Duration                                 : 2h 38mn
Bit rate mode                            : Variable
Bit rate                                 : 114 bps
Stream size                              : 132 KiB (0%)
Title                                    : Core Media Subtitle
Language                                 : French
Default                                  : No
Forced                                   : No
Encoded date                             : UTC 2015-08-21 19:04:30
Tagged date                              : UTC 2015-08-21 19:05:34
Alternate Group                          : 1

Text #6
ID                                       : 8
Format                                   : Timed Text
Muxing mode                              : sbtl
Codec ID                                 : tx3g
Duration                                 : 2h 38mn
Bit rate mode                            : Variable
Bit rate                                 : 88 bps
Stream size                              : 101 KiB (0%)
Title                                    : Core Media Subtitle
Language                                 : Portuguese
Default                                  : No
Forced                                   : No
Encoded date                             : UTC 2015-08-21 19:04:30
Tagged date                              : UTC 2015-08-21 19:05:34
Alternate Group                          : 1

Menu
ID                                       : 9
Codec ID                                 : tx3g
Duration                                 : 2h 45mn
Title                                    : Core Media Text
Language                                 : English
Encoded date                             : UTC 2015-08-21 19:04:30
Tagged date                              : UTC 2015-08-21 19:05:34
Menu For                                 : 2,11,12
00:00:00.000                             : Chapter 1
00:06:51.000                             : Chapter 2
00:14:33.000                             : Chapter 3
00:21:37.000                             : Chapter 4
00:30:13.000                             : Chapter 5
00:38:45.000                             : Chapter 6
00:46:08.000                             : Chapter 7
00:51:39.000                             : Chapter 8
00:59:09.000                             : Chapter 9
01:07:48.000                             : Chapter 10
01:15:14.000                             : Chapter 11
01:23:25.000                             : Chapter 12
01:29:14.000                             : Chapter 13
01:37:16.000                             : Chapter 14
01:44:35.000                             : Chapter 15
01:51:25.000                             : Chapter 16
01:57:48.000                             : Chapter 17
02:04:48.000                             : Chapter 18
02:12:35.000                             : Chapter 19
02:21:04.000                             : Chapter 20
02:28:48.000                             : Chapter 21
02:37:09.000                             : Chapter 22
Bit rate mode                            : VBR
```

```
General
Complete name                            : Z:\Phineas and Ferb the Movie_ Across t.m4v
Format                                   : MPEG-4
Codec ID                                 : M4V  (M4V /mp42/isom)
File size                                : 3.12 GiB
Duration                                 : 1h 16mn
Overall bit rate mode                    : Variable
Overall bit rate                         : 5 793 Kbps
Movie name                               : Phineas and Ferb the Movie: Across the 2nd Dimension
Performer                                : Dan Povenmire & Robert F. Hughes
Performer/Sorted by                      : Dan Povenmire & Robert F. Hughes
Director                                 : Dan Povenmire / Robert F. Hughes
Actor                                    : Vincent Martella / Ashley Tisdale / Thomas Sangster
Screenplay by                            : Jon Colton Barry / Jeff "Swampy" Marsh
Production studio                        : Disney XD
Genre                                    : Kids & Family
ContentType                              : Short Film
Description                              : In "Phineas and Ferb: Across the 2nd Dimension," the boys finally discover that their beloved pet platypus Perry is in fact a secret agent who battles the forces of evil daily. They join him on an adventure that blasts them to another dimension where a tr
Recorded date                            : UTC 2011-08-05 07:00:00
Encoded date                             : UTC 2014-07-18 12:51:23
Tagged date                              : UTC 2014-07-18 12:52:05
Copyright                                : © 2011 Disney XD
Cover                                    : Yes
Rating                                   : None
AppleStoreAccount                        : muffins@evil.inc
AppleStoreCatalogID                      : 442913680
GenreID                                  : 4410
AppleStoreCountry                        : Zimbabwe
PurchaseDate                             : 1666-06-06 06:06:06
Title/Sort                               : Phineas and Ferb the Movie: Across the 2nd Dimension
Vendor                                   : buenavista:vendor_id:PFA0NNG1_WDSHE
Flavour                                  : 6:60p
ContentRating                            : au-movie|G|100|
LongDescription                          : In "Phineas and Ferb: Across the 2nd Dimension," the boys finally discover that their beloved pet platypus Perry is in fact a secret agent who battles the forces of evil daily. They join him on an adventure that blasts them to another dimension where a truly evil Dr. Doofenshmirtz has taken over an alternate Tri-state Area. When they uncover his plot to travel back to their dimension to take over their Tri-state Area, the gang, as well as their alter-egos, must band together to stop him.
copy-warning                             : &nbsp;

Video #1
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1h 16mn
Bit rate                                 : 5 081 Kbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (23976/1000) fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.102
Stream size                              : 2.73 GiB (88%)
Language                                 : English
Default                                  : Yes
Encoded date                             : UTC 2014-07-18 12:51:17
Tagged date                              : UTC 2014-07-18 12:52:05
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Video #2
ID                                       : 11
Format                                   : JPEG
Codec ID                                 : jpeg
Duration                                 : 1h 16mn
Bit rate mode                            : Variable
Bit rate                                 : 4 906 bps
Width                                    : 640 pixels
Height                                   : 360 pixels
Display aspect ratio                     : 1.85:1
Frame rate mode                          : Variable
Frame rate                               : 0.003 fps
Minimum frame rate                       : 0.001 fps
Maximum frame rate                       : 0.006 fps
Color space                              : YUV
Chroma subsampling                       : 4:4:4
Bit depth                                : 8 bits
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 7.098
Stream size                              : 2.34 MiB (0%)
Language                                 : English
Default                                  : No
Encoded date                             : UTC 2014-07-18 12:51:18
Tagged date                              : UTC 2014-07-18 12:52:05

Audio #1
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 1h 16mn
Source duration                          : 1h 16mn
Bit rate mode                            : Constant
Bit rate                                 : 160 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 46.875 fps (1024 spf)
Compression mode                         : Lossy
Stream size                              : 86.6 MiB (3%)
Source stream size                       : 86.6 MiB (3%)
Language                                 : English
Default                                  : Yes
Encoded date                             : UTC 2014-07-18 12:51:18
Tagged date                              : UTC 2014-07-18 12:52:05
Alternate Group                          : 1
Menus                                    : 10,11
Fallback From                            : 3
Subtitles                                : 4

Audio #2
ID                                       : 3
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : ac-3
Duration                                 : 1h 16mn
Bit rate mode                            : Constant
Bit rate                                 : 384 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Frame rate                               : 31.250 fps (1536 spf)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 211 MiB (7%)
Language                                 : English
Default                                  : Inherited From: 2
Encoded date                             : UTC 2014-07-18 12:51:18
Tagged date                              : UTC 2014-07-18 12:52:05
Alternate Group                          : 1
Menus                                    : 10,11
Fallback To                              : 2
Subtitles                                : 4

Audio #3
ID                                       : 5
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 1h 16mn
Source duration                          : 1h 16mn
Bit rate mode                            : Constant
Bit rate                                 : 160 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 46.875 fps (1024 spf)
Compression mode                         : Lossy
Stream size                              : 86.3 MiB (3%)
Source stream size                       : 86.3 MiB (3%)
Language                                 : Spanish
Default                                  : No
Encoded date                             : UTC 2014-07-18 12:51:18
Tagged date                              : UTC 2014-07-18 12:52:05
Alternate Group                          : 1
Menus                                    : 10,11
Subtitles                                : 6

Text #1
ID                                       : 4
Format                                   : Timed Text
Muxing mode                              : sbtl
Codec ID                                 : tx3g
Duration                                 : 1s 0ms
Bit rate                                 : 88 bps
Stream size                              : 11.0 Bytes (0%)
Language                                 : English
Default                                  : Yes
Forced                                   : Yes
Encoded date                             : UTC 2014-07-18 12:51:18
Tagged date                              : UTC 2014-07-18 12:52:05
Alternate Group                          : 2
Subtitles For                            : 2,3

Text #2
ID                                       : 6
Format                                   : Timed Text
Muxing mode                              : sbtl
Codec ID                                 : tx3g
Duration                                 : 1h 15mn
Source duration                          : 1h 15mn
Bit rate mode                            : Variable
Bit rate                                 : 3 bps
Stream size                              : 1.62 KiB (0%)
Source stream size                       : 1.62 KiB (0%)
Language                                 : Spanish
Default                                  : No
Forced                                   : Yes
Encoded date                             : UTC 2014-07-18 12:51:18
Tagged date                              : UTC 2014-07-18 12:52:05
Alternate Group                          : 2
Subtitles For                            : 5
Full Alternative                         : 7

Text #3
ID                                       : 7
Format                                   : Timed Text
Muxing mode                              : sbtl
Codec ID                                 : tx3g
Duration                                 : 1h 15mn
Source duration                          : 1h 15mn
Bit rate mode                            : Variable
Bit rate                                 : 149 bps
Stream size                              : 82.9 KiB (0%)
Source stream size                       : 82.9 KiB (0%)
Language                                 : Spanish
Default                                  : No
Forced                                   : No
Encoded date                             : UTC 2014-07-18 12:51:18
Tagged date                              : UTC 2014-07-18 12:52:05
Alternate Group                          : 2
Subtitles For                            : 5
Forced Alternative                       : 6

Text #4
ID                                       : 8
Format                                   : Timed Text
Muxing mode                              : sbtl
Codec ID                                 : tx3g
Duration                                 : 1h 15mn
Source duration                          : 1h 15mn
Bit rate mode                            : Variable
Bit rate                                 : 138 bps
Stream size                              : 76.7 KiB (0%)
Source stream size                       : 76.7 KiB (0%)
Language                                 : Finnish
Default                                  : No
Forced                                   : No
Encoded date                             : UTC 2014-07-18 12:51:18
Tagged date                              : UTC 2014-07-18 12:52:05
Alternate Group                          : 2

Text #5
ID                                       : 9-CC1
Format                                   : EIA-608
Muxing mode                              : Final Cut
Codec ID                                 : c608
Duration                                 : 1h 15mn
Source duration                          : 1h 15mn
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)
Source stream size                       : 90.0 KiB (0%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
Encoded date                             : UTC 2014-07-18 12:51:18
Tagged date                              : UTC 2014-07-18 12:52:05

Menu
ID                                       : 10
Codec ID                                 : tx3g
Duration                                 : 1h 16mn
Language                                 : English
Encoded date                             : UTC 2014-07-18 12:51:18
Tagged date                              : UTC 2014-07-18 12:52:05
Menu For                                 : 2,3,5
00:00:00.000                             : Everything's Better With Perry
00:04:10.000                             : Agent P
00:08:12.000                             : Doofenshmirtz Evil Inc.
00:15:01.000                             : Brand New Best Friend
00:26:21.000                             : Summer
00:33:52.000                             : The Resistance
00:39:22.000                             : Agent P Rescue
00:46:05.000                             : Doom!
00:52:43.000                             : Portals
00:58:47.000                             : Robot Riot
01:05:20.000                             : Evilness Diminishing
01:14:21.000                             : Forgetting The Best Day Ever
Bit rate mode                            : VBR

```

It may be a bit much but...  That's what's in the file.

**Comment by JeromeMartinez** [comment]
> It keeps complaining that "Flags" is undefined. Apparently Skip_Flags and Get_Flags have different ways of accessing things depending on the settings. I have noooo idea how the hell to fix that.

Should be transparent for you.
I can deal with that, no problem. Will give feedback later.

**Comment by ndjamena** [comment]
I've got it compiling in release, I'm not sure what Info_B4 is supposed to do, where the "flag" variable came from in debug mode and why it was giving the correct values...

Filezilla says the password you gave me is wrong, so I can't upload any samples, I'm surprised no one has given you an iTunes movie before.  I guess this isn't that important.

**Comment by JeromeMartinez** [comment]
As an overal view, the PR is interesting, lot of new interesting fields, but unfortunately I don't have sample files for all cases.
Anyway, let's start with this patch, but as "unstable", the feature may change in the future (different behaviour, different field names...)

**Pull request merged**
