### PR TITLE
HEVC: Trying to better support buggy SEIs (missing rbsp_stop_one_bit)

### PR DESCRIPTION
**Pull request by JeromeMartinez**
At some point we should add messages when there is an error in the bitstream, but for the moment I didn't figure the best approach (with generic code for handling errors as much as possible, and not poluting the default output)

From vote https://mediaarea.net/Vote/Support-Buggy-Hevc-H-265-Sei-171
Issue from encoder, see https://github.com/rigaya/NVEnc/issues/51#issuecomment-393130636

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
ping @pwacooijmans

**Comment by pwacooijmans** [comment]
:)

2018-06-01 12:18 GMT+02:00 Jérôme Martinez <notifications@github.com>:

**Comment by pwacooijmans** [comment]
Well thx for the some point at least, lets hope it doesn't take another year :)

**Comment by pwacooijmans** [comment]
but to be honest just add a commandline message or something to log the
thing....and a log in the gui....everyone happy....all it needs to say is
OK or CORRUPT per item...everyone happy :)


2018-06-01 12:26 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
so to give an example: nal1: ok, nal 2: ok, nal-sei: ok and some oks about
the rest of the streams EVERYONE happy and yet NO important details given

2018-06-01 12:38 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
don't make it too complicated...the avg consumer using mediainfo has no
clue whatsoever

2018-06-01 12:43 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
They are just happy if they get all the checks in the checklist :)

2018-06-01 12:48 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
you went well out of your time zone there to fix this, thanks a LOT for such dedicated commitment to making the world a better place for all of us :)

**Comment by JeromeMartinez** [comment]
[Windows snapshot having this update](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20180601-4/MediaInfo_GUI_18.05.20180601_Windows.exe)

**Comment by pwacooijmans** [comment]
thx a LOT :)
awesome job :)

**Comment by pwacooijmans** [comment]
Well thx to you I can say now with 100% certainty that it's a total loss of
files due to this bug :(...however on the bright side it's better than
figuring this out after 10 years :)

2018-06-01 17:59 GMT+02:00 Jérôme Martinez <notifications@github.com>:

**Comment by pwacooijmans** [comment]
I mean it's not like I don't want to retire someday :)

2018-06-01 20:07 GMT+02:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Pull request merged**
